WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
----------------------- Проверка flake8 пройдена -----------------------

============================= test session starts ==============================
platform linux -- Python 3.7.4, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python
django: settings: yatube.settings (from env)
rootdir: /app, configfile: pytest.ini
plugins: Faker-12.0.1, django-4.4.0, pythonpath-0.7.3
collecting ... collected 28 items

yatube/posts/tests/test_forms.py::PostFormTest::test_post_create PASSED  [  3%]
yatube/posts/tests/test_forms.py::PostFormTest::test_post_edit PASSED    [  7%]
yatube/posts/tests/test_forms.py::CommentFormTest::test_add_comment PASSED [ 10%]
yatube/posts/tests/test_forms.py::CommentFormTest::test_add_comment_valid PASSED [ 14%]
yatube/posts/tests/test_models.py::PostModelTest::test_group_model_have_correct_object_names PASSED [ 17%]
yatube/posts/tests/test_models.py::PostModelTest::test_post_model_have_correct_object_names PASSED [ 21%]
yatube/posts/tests/test_urls.py::PostURLTests::test_group_list_exists_at_desired_location PASSED [ 25%]
yatube/posts/tests/test_urls.py::PostURLTests::test_home_url_exists_at_desired_location PASSED [ 28%]
yatube/posts/tests/test_urls.py::PostURLTests::test_post_create_url_redirect_anonymous_on_admin_login PASSED [ 32%]
yatube/posts/tests/test_urls.py::PostURLTests::test_post_detail_exists_at_desired_location PASSED [ 35%]
yatube/posts/tests/test_urls.py::PostURLTests::test_post_edit_url_redirect_not_author_on_post_detail PASSED [ 39%]
yatube/posts/tests/test_urls.py::PostURLTests::test_profile_exists_at_desired_location PASSED [ 42%]
yatube/posts/tests/test_urls.py::PostURLTests::test_urls_uses_correct_template PASSED [ 46%]
yatube/posts/tests/test_urls.py::PostURLTests::test_urls_uses_correct_unexisting_page FAILED [ 50%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_add_comment_show_correct_context PASSED [ 53%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_created_posts_shows_on_different_pages PASSED [ 57%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_group_posts_show_correct_context PASSED [ 60%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_index_show_correct_context PASSED [ 64%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_pages_use_correct_templates PASSED [ 67%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_post_create_show_correct_context PASSED [ 71%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_post_detail_show_correct_context PASSED [ 75%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_post_edit_show_correct_context PASSED [ 78%]
yatube/posts/tests/test_views.py::TestsViewsPosts::test_profile_show_correct_context PASSED [ 82%]
yatube/posts/tests/test_views.py::PaginatorViewsTest::test_firsts_page_contains_ten_records PASSED [ 85%]
yatube/posts/tests/test_views.py::PaginatorViewsTest::test_second_page_contains_ten_records PASSED [ 89%]
yatube/posts/tests/test_views.py::IndexCacheTests::test_cache_index_page PASSED [ 92%]
yatube/posts/tests/test_views.py::FollowTests::test_follow_unfollow PASSED [ 96%]
yatube/posts/tests/test_views.py::FollowTests::test_view_new_follow_post PASSED [100%]

=================================== FAILURES ===================================
_____________ PostURLTests.test_urls_uses_correct_unexisting_page ______________

self = <posts.tests.test_urls.PostURLTests testMethod=test_urls_uses_correct_unexisting_page>

    def test_urls_uses_correct_unexisting_page(self):
        response = self.guest_client.get('/unexisting_page/')
>       self.assertEqual(response.status_code, HTTPStatus.OK)
E       AssertionError: 404 != <HTTPStatus.OK: 200>

yatube/posts/tests/test_urls.py:79: AssertionError
------------------------------ Captured log call -------------------------------
WARNING  django.request:log.py:228 Not Found: /unexisting_page/
=========================== short test summary info ============================
FAILED yatube/posts/tests/test_urls.py::PostURLTests::test_urls_uses_correct_unexisting_page
========================= 1 failed, 27 passed in 1.36s =========================
======================== Ваши тесты не работают ========================